### ISSUE TITLE
Can't create/edit Strategy "ActionView::Template::Error (undefined method `self_care_strategy')"

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#360]
This bug was introduced after https://github.com/julianguyen/ifme/pull/355 was merged and deployed.

```
  app/views/strategies/_form.html.erb:29:in `block in _app_views_strategies__form_html_erb___1995940113129812464_70151665889660'
  app/views/strategies/_form.html.erb:1:in `_app_views_strategies__form_html_erb___1995940113129812464_70151665889660'
  app/views/strategies/edit.html.erb:2:in `_app_views_strategies_edit_html_erb__3388630339756945431_70151666039760'
  app/controllers/application_controller.rb:27:in `block in with_timezone'
  app/controllers/application_controller.rb:27:in `with_timezone'
```

**Comment by julianguyen** [comment]
Ah ok so the issue is that we're missing a missing a migration file that adds `self_care_strategy` and `daily_reminder_email` to the Strategy model.

**Comment by julianguyen** [comment]
I am going to fix this right now.

**Comment by julianguyen** [comment]
I'm reverting your changes @andela-oesho. Left some more comments in your original PR!
